# Generated by Django 4.0.6 on 2022-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='owner_name',
            field=models.CharField(max_length=50),
        ),
    ]
