# Generated by Django 4.0.6 on 2022-12-13 07:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='Pending', max_length=50)),
                ('occupancy_adult', models.PositiveIntegerField()),
                ('occupancy_child', models.PositiveIntegerField()),
                ('guest_name', models.CharField(default='-', max_length=50)),
                ('guest_mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('total', models.FloatField(default=0)),
                ('stay_start_date', models.DateField()),
                ('stay_end_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('address', models.TextField(max_length=120)),
                ('location', models.CharField(max_length=50)),
                ('star_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('availability', models.CharField(choices=[('booked', 'Booked'), ('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=50)),
                ('price_of_adult', models.FloatField(default=2000.0)),
                ('price_of_child', models.FloatField(default=1000.0)),
                ('occupancy_adult', models.PositiveIntegerField()),
                ('occupancy_child', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hotel', to='Hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PerDayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='Pending', max_length=50)),
                ('bookingss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.room'),
        ),
    ]
