# Generated by Django 4.0.6 on 2022-11-16 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Open', 'Open'), ('inactive', 'inactive')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='Hotel.hotel'),
        ),
    ]
