# Generated by Django 4.0.6 on 2022-11-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_bookings',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
