# Generated by Django 4.0.6 on 2022-11-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_booking_total_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
