# Generated by Django 4.0.6 on 2022-11-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='type_of_user',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Hotel', 'Hotel'), ('Guest', 'Guest')], default='Guest', max_length=50),
        ),
    ]
