# Generated by Django 4.0.6 on 2022-11-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_hotel_type_of_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='hotel_name',
        ),
    ]
