# Generated by Django 4.0.6 on 2022-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_room_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(default='guest', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
