# Generated by Django 4.0.6 on 2022-11-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_booking_total_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_bookings',
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
