# Generated by Django 4.0.6 on 2022-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_remove_booking_total_bookings_hotel_total_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_bookingss',
            field=models.IntegerField(default=0),
        ),
    ]
