# Generated by Django 4.0.6 on 2022-11-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_rename_name_hotel_hotel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_name',
            new_name='hotel',
        ),
    ]
