# Generated by Django 4.0.6 on 2022-11-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_booking_guest_mobile_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Active', 'Active'), ('inactive', 'inactive')], default='Open', max_length=50),
        ),
    ]
