# Generated by Django 4.0.6 on 2022-11-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_booking_total_bookingss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_bookingss',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='total_bookings',
        ),
    ]
