# Generated by Django 4.0.6 on 2022-11-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_alter_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=2000.0),
        ),
    ]
