# Generated by Django 4.0.6 on 2022-11-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_remove_booking_total_bookingss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerDayBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.booking')),
            ],
        ),
    ]
