# Generated by Django 4.0.6 on 2022-11-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_alter_hotel_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
