# Generated by Django 4.0.6 on 2022-11-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_alter_hotel_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel',
            new_name='hotel_name',
        ),
    ]
