# Generated by Django 4.0.6 on 2022-11-17 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_alter_booking_guest_mobile_alter_booking_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stay_end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
