# Generated by Django 4.0.6 on 2022-11-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_rename_booking_perdaybooking_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perdaybooking',
            old_name='booking',
            new_name='bookingss',
        ),
    ]
