# Generated by Django 4.0.6 on 2022-11-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_rename_hotel_hotel_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name',
        ),
    ]
