# Generated by Django 4.0.6 on 2022-11-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_rename_booking_perdaybooking_bookingss'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdaybooking',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Accepted', max_length=50),
        ),
    ]
