# Generated by Django 4.0.6 on 2022-11-17 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_alter_booking_stay_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stay_end_date',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stay_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
