# Generated by Django 4.0.6 on 2022-11-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_perdaybooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdaybooking',
            name='status',
        ),
    ]
