# Generated by Django 4.0.6 on 2022-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0011_alter_booking_stay_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stay_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stay_start_date',
            field=models.DateField(),
        ),
    ]
