# Generated by Django 4.0.6 on 2022-11-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0012_alter_booking_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdaybooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('vacated', 'vacated')], default='Active', max_length=50),
            preserve_default=False,
        ),
    ]
