# Generated by Django 4.0.6 on 2022-11-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0012_alter_booking_stay_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='no_of_days',
        ),
    ]
