# Generated by Django 4.0.6 on 2022-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0013_remove_booking_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_days',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
