# Generated by Django 4.0.6 on 2022-11-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0014_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdaybooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('vacate', 'vacate')], default='Active', max_length=50),
        ),
    ]
