# Generated by Django 4.0.6 on 2022-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0014_booking_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
