# Generated by Django 4.0.6 on 2022-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0015_alter_booking_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
