# Generated by Django 4.0.6 on 2022-11-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0016_alter_booking_guest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='price_of_adult',
        ),
        migrations.AddField(
            model_name='room',
            name='price_of_child',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Active', 'Active'), ('inactive', 'inactive')], default='Active', max_length=50),
        ),
    ]
