# Generated by Django 4.0.6 on 2022-12-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0017_alter_perdaybooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='perdaybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('booked', 'Booked'), ('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
