# Generated by Django 4.0.6 on 2022-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0018_room_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
