# Generated by Django 4.0.6 on 2022-11-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0019_booking_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_price',
        ),
    ]
